# Generated by Django 3.2.4 on 2021-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='publish_date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
